@database = BigBoxStore
@collection = GroceryInventory
@domain = http://localhost
@port = 3000
@id = 673bc83bfd0a32baafabf9a0

###
GET {{domain}}:{{port}}/find/{{database}}/{{collection}}
Content-Type: application/json

###
POST {{domain}}:{{port}}/insert/{{database}}/{{collection}}
Content-Type: application/json

{
    "item": "cashews",
    "food_group": "nuts",
    "price_in_usd": 5,
}


###
PUT {{domain}}:{{port}}/update/{{database}}/{{collection}}/{{id}}
Content-Type: application/json

{
    "item": "coconut"
}

###
DELETE {{domain}}:{{port}}/delete/{{database}}/{{collection}}/{{id}}
Content-Type: application/json

### Delete a Collection from a Database
DELETE {{domain}}:{{port}}/delete-collection/{{database}}/{{collection}}
Content-Type: application/json

